/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.prj1.GUI;

/**
 *
 * @author WINDOWS
 */
public class KetCa_ extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KetCa_.class.getName());
    private boolean ketCaThanhCong = false;
    private double tongTienKetCa = 0;

    private String tenNhanVien;
    private String maNhanVien;
    private String tenCaLam;
    private String thoiGianCaLam;
    private java.time.LocalDateTime thoiGianMoCa;
    /**
     * Creates new form KetCa_
     */
    public KetCa_(
        java.awt.Frame parent,
        boolean modal,
        String tenNhanVien,
        String maNhanVien,
        String tenCaLam,
        String thoiGianCaLam,
        java.time.LocalDateTime thoiGianMoCa
) {
    super(parent, modal);

    this.tenNhanVien = tenNhanVien;
    this.maNhanVien = maNhanVien;
    this.tenCaLam = tenCaLam;
    this.thoiGianCaLam = thoiGianCaLam;
    this.thoiGianMoCa = thoiGianMoCa;

    initComponents();

    hienThiThongTinKetCa();
    canChinhGiaoDienKetCa();

    jButton1.addActionListener(e -> xacNhanKetCa());
    jButton2.addActionListener(e -> dispose());
}
    public KetCa_(java.awt.Frame parent, boolean modal) {
    this(parent, modal, "", "", "", "", null);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kết ca làm việc");
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông tin ca làm"));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Tên nhân viên:");
        jPanel5.add(jLabel2);

        jLabel3.setText("jLabel3");
        jPanel5.add(jLabel3);

        jLabel6.setText("Ca làm: ");
        jPanel5.add(jLabel6);

        jLabel7.setText("jLabel7");
        jPanel5.add(jLabel7);

        jPanel3.add(jPanel5);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setText("Mã nhân viên:");
        jPanel6.add(jLabel4);

        jLabel5.setText("jLabel5");
        jPanel6.add(jLabel5);

        jPanel3.add(jPanel6);

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.X_AXIS));

        jLabel8.setText("Thời gian kết ca: ");
        jPanel8.add(jLabel8);

        jLabel9.setText("jLabel9");
        jPanel8.add(jLabel9);

        jPanel3.add(jPanel8);

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.X_AXIS));

        jLabel10.setText("Thời gian làm việc:");
        jPanel9.add(jLabel10);

        jLabel11.setText("jLabel11");
        jPanel9.add(jLabel11);

        jPanel3.add(jPanel9);

        jPanel1.add(jPanel3);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nhập số lượng tiền cuối ca"));
        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.Y_AXIS));

        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.X_AXIS));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/prj1/img/1nghin (1).jpg"))); // NOI18N
        jLabel12.setText("1.000₫  ");
        jPanel11.add(jLabel12);

        jTextField1.setText("jTextField1");
        jPanel11.add(jTextField1);

        jLabel13.setText("tờ");
        jPanel11.add(jLabel13);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/prj1/img/100nghin (1).jpg"))); // NOI18N
        jLabel34.setText("100.000₫");
        jPanel11.add(jLabel34);

        jTextField13.setText("jTextField7");
        jPanel11.add(jTextField13);

        jLabel35.setText("tờ");
        jPanel11.add(jLabel35);

        jPanel10.add(jPanel11);

        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.X_AXIS));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/prj1/img/2nghin (1).jpg"))); // NOI18N
        jLabel14.setText("2.000₫  ");
        jPanel12.add(jLabel14);

        jTextField2.setText("jTextField2");
        jPanel12.add(jTextField2);

        jLabel15.setText("tờ");
        jPanel12.add(jLabel15);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/prj1/img/200nghin (1).jpg"))); // NOI18N
        jLabel30.setText("200.000₫");
        jPanel12.add(jLabel30);

        jTextField11.setText("jTextField8");
        jPanel12.add(jTextField11);

        jLabel31.setText("tờ");
        jPanel12.add(jLabel31);

        jPanel10.add(jPanel12);

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.X_AXIS));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/prj1/img/5nghin (1).jpg"))); // NOI18N
        jLabel16.setText("5.000₫  ");
        jPanel13.add(jLabel16);

        jTextField3.setText("jTextField3");
        jPanel13.add(jTextField3);

        jLabel17.setText("tờ");
        jPanel13.add(jLabel17);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/prj1/img/500nghin (1).jpg"))); // NOI18N
        jLabel36.setText("500.000₫");
        jPanel13.add(jLabel36);

        jTextField14.setText("jTextField9");
        jPanel13.add(jTextField14);

        jLabel37.setText("tờ");
        jPanel13.add(jLabel37);

        jPanel10.add(jPanel13);

        jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.LINE_AXIS));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/prj1/img/10nghin (1).jpg"))); // NOI18N
        jLabel18.setText("10.000₫");
        jPanel14.add(jLabel18);

        jTextField4.setText("jTextField4");
        jPanel14.add(jTextField4);

        jLabel19.setText("tờ");
        jPanel14.add(jLabel19);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/prj1/img/20nghin (1).jpg"))); // NOI18N
        jLabel20.setText("20.000₫");
        jPanel14.add(jLabel20);

        jTextField5.setText("jTextField5");
        jPanel14.add(jTextField5);

        jLabel21.setText("tờ");
        jPanel14.add(jLabel21);

        jPanel10.add(jPanel14);

        jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.LINE_AXIS));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/prj1/img/50nghin (1).jpg"))); // NOI18N
        jLabel22.setText("50.000₫");
        jPanel16.add(jLabel22);

        jTextField6.setText("jTextField6");
        jPanel16.add(jTextField6);

        jLabel24.setText("tờ");
        jPanel16.add(jLabel24);

        jPanel10.add(jPanel16);

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.X_AXIS));

        jLabel23.setText("Tiền chuyển khoản(nếu có):");
        jPanel4.add(jLabel23);

        jTextField7.setText("jTextField7");
        jPanel4.add(jTextField7);

        jLabel25.setText("₫ ");
        jPanel4.add(jLabel25);

        jPanel10.add(jPanel4);

        jPanel1.add(jPanel10);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(242, 242, 242));
        jButton1.setText("Kết ca");
        jPanel2.add(jButton1);

        jButton2.setText("Hủy");
        jPanel2.add(jButton2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                KetCa_ dialog = new KetCa_(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
public boolean isKetCaThanhCong() {
    return ketCaThanhCong;
}

public double getTongTienKetCa() {
    return tongTienKetCa;
}

private void hienThiThongTinKetCa() {
    java.time.format.DateTimeFormatter fmt =
            java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");

    java.time.LocalDateTime thoiGianKetCa = java.time.LocalDateTime.now();

    // Tên nhân viên
    jLabel3.setText(tenNhanVien == null ? "" : tenNhanVien);

    // Mã nhân viên
    jLabel5.setText(maNhanVien == null ? "" : maNhanVien);

    // Ca làm
    jLabel7.setText(tenCaLam == null ? "" : tenCaLam);

    // Thời gian kết ca
    jLabel9.setText(thoiGianKetCa.format(fmt));

    // Thời gian làm thực tế
    jLabel11.setText(tinhThoiGianLamViec(thoiGianMoCa, thoiGianKetCa));
}
    private void canChinhGiaoDienKetCa() {
    setSize(750, 630);
    setLocationRelativeTo(getParent());
    setResizable(false);

    jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 22));
    jLabel1.setForeground(new java.awt.Color(0, 102, 204));
    jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 0, 12, 0));

    jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 20, 8, 20));

    jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createTitledBorder(
                    javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)),
                    "Thông tin ca làm"
            ),
            javax.swing.BorderFactory.createEmptyBorder(8, 15, 8, 15)
    ));

    jPanel10.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createTitledBorder(
                    javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)),
                    "Nhập số lượng tiền cuối ca"
            ),
            javax.swing.BorderFactory.createEmptyBorder(8, 15, 8, 15)
    ));
    canChinhDongNhanVienVaCaLam();
    javax.swing.JPanel[] dongThongTin = {
        jPanel5, jPanel6, jPanel8, jPanel9
    };

    for (javax.swing.JPanel p : dongThongTin) {
        p.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 5, 4, 5));
        p.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 32));
    }

    javax.swing.JLabel[] labelTieuDe = {
        jLabel2, jLabel4, jLabel6, jLabel8, jLabel10
    };

    for (javax.swing.JLabel lbl : labelTieuDe) {
        lbl.setPreferredSize(new java.awt.Dimension(130, 25));
        lbl.setMinimumSize(new java.awt.Dimension(130, 25));
        lbl.setMaximumSize(new java.awt.Dimension(130, 25));
        lbl.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
    }

    javax.swing.JLabel[] labelGiaTri = {
        jLabel3, jLabel5, jLabel7, jLabel9, jLabel11
    };

    for (javax.swing.JLabel lbl : labelGiaTri) {
        lbl.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        lbl.setForeground(new java.awt.Color(0, 102, 204));
    }

    javax.swing.JPanel[] dongTien = {
        jPanel11, jPanel12, jPanel13, jPanel14, jPanel16
    };

    for (javax.swing.JPanel p : dongTien) {
        p.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        p.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 50));
    }

    javax.swing.JTextField[] txtTien = {
        jTextField1,
        jTextField2,
        jTextField3,
        jTextField4,
        jTextField5,
        jTextField6,
        jTextField13,
        jTextField11,
        jTextField14,
        jTextField7
    };

    for (javax.swing.JTextField txt : txtTien) {
        txt.setText("0");
        txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt.setPreferredSize(new java.awt.Dimension(85, 30));
        txt.setMaximumSize(new java.awt.Dimension(85, 30));
        txt.setMinimumSize(new java.awt.Dimension(85, 30));
        chiChoNhapSo(txt);
    }

    jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 0, 12, 0));

    jButton1.setPreferredSize(new java.awt.Dimension(120, 35));
    jButton2.setPreferredSize(new java.awt.Dimension(120, 35));

    // Dòng 1: 1.000 + 100.000
    canChinhDongTienDoi(
            jPanel11,
            jLabel12, jTextField1, jLabel13,
            jLabel34, jTextField13, jLabel35
    );

    // Dòng 2: 2.000 + 200.000
    canChinhDongTienDoi(
            jPanel12,
            jLabel14, jTextField2, jLabel15,
            jLabel30, jTextField11, jLabel31
    );

    // Dòng 3: 5.000 + 500.000
    canChinhDongTienDoi(
            jPanel13,
            jLabel16, jTextField3, jLabel17,
            jLabel36, jTextField14, jLabel37
    );

    // Dòng 4: 10.000 + 20.000
    canChinhDongTienDoi(
            jPanel14,
            jLabel18, jTextField4, jLabel19,
            jLabel20, jTextField5, jLabel21
    );
    canChinhDongThongTinDon(jPanel6, jLabel4, jLabel5);
    canChinhDongThongTinDon(jPanel8, jLabel8, jLabel9);
    canChinhDongThongTinDon(jPanel9, jLabel10, jLabel11);
    // jPanel15 đang rỗng, ẩn đi để không chiếm chiều cao
    

    // Dòng 5: 50.000 + tiền chuyển khoản
    canChinhDongTienVaChuyenKhoan(
            jPanel16,
            jLabel22, jTextField6, jLabel24,
            jLabel23, jTextField7, jLabel25
    );

    // Không dùng dòng chuyển khoản riêng nữa
    jPanel4.setVisible(false);
    jPanel4.setMaximumSize(new java.awt.Dimension(0, 0));

    jPanel1.revalidate();
    jPanel1.repaint();
}

private void chiChoNhapSo(javax.swing.JTextField txt) {
    txt.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyTyped(java.awt.event.KeyEvent e) {
            char c = e.getKeyChar();

            if (!Character.isDigit(c)) {
                e.consume();
            }
        }
    });
}



private void canChinhDongTienDoi(
        javax.swing.JPanel panel,
        javax.swing.JLabel lbl1,
        javax.swing.JTextField txt1,
        javax.swing.JLabel lblTo1,
        javax.swing.JLabel lbl2,
        javax.swing.JTextField txt2,
        javax.swing.JLabel lblTo2
) {
    panel.removeAll();
    panel.setLayout(new javax.swing.BoxLayout(panel, javax.swing.BoxLayout.X_AXIS));

    java.awt.Dimension sizeLabel = new java.awt.Dimension(140, 35);

    lbl1.setPreferredSize(sizeLabel);
    lbl1.setMinimumSize(sizeLabel);
    lbl1.setMaximumSize(sizeLabel);

    lbl2.setPreferredSize(sizeLabel);
    lbl2.setMinimumSize(sizeLabel);
    lbl2.setMaximumSize(sizeLabel);

    panel.add(lbl1);
    panel.add(javax.swing.Box.createHorizontalStrut(8));
    panel.add(txt1);
    panel.add(javax.swing.Box.createHorizontalStrut(5));
    panel.add(lblTo1);

    panel.add(javax.swing.Box.createHorizontalStrut(60));

    panel.add(lbl2);
    panel.add(javax.swing.Box.createHorizontalStrut(8));
    panel.add(txt2);
    panel.add(javax.swing.Box.createHorizontalStrut(5));
    panel.add(lblTo2);

    panel.revalidate();
    panel.repaint();
}
private void canChinhDongTienVaChuyenKhoan(
        javax.swing.JPanel panel,
        javax.swing.JLabel lblTienMat,
        javax.swing.JTextField txtTienMat,
        javax.swing.JLabel lblTo,
        javax.swing.JLabel lblChuyenKhoan,
        javax.swing.JTextField txtChuyenKhoan,
        javax.swing.JLabel lblDonVi
) {
    panel.removeAll();
    panel.setLayout(new javax.swing.BoxLayout(panel, javax.swing.BoxLayout.X_AXIS));

    java.awt.Dimension sizeLabelTien = new java.awt.Dimension(140, 35);
    lblTienMat.setPreferredSize(sizeLabelTien);
    lblTienMat.setMinimumSize(sizeLabelTien);
    lblTienMat.setMaximumSize(sizeLabelTien);

    lblChuyenKhoan.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
    lblChuyenKhoan.setPreferredSize(new java.awt.Dimension(180, 35));
    lblChuyenKhoan.setMinimumSize(new java.awt.Dimension(180, 35));
    lblChuyenKhoan.setMaximumSize(new java.awt.Dimension(180, 35));

    txtChuyenKhoan.setPreferredSize(new java.awt.Dimension(120, 30));
    txtChuyenKhoan.setMaximumSize(new java.awt.Dimension(120, 30));
    txtChuyenKhoan.setMinimumSize(new java.awt.Dimension(120, 30));
    txtChuyenKhoan.setHorizontalAlignment(javax.swing.JTextField.CENTER);

    panel.add(lblTienMat);
    panel.add(javax.swing.Box.createHorizontalStrut(8));
    panel.add(txtTienMat);
    panel.add(javax.swing.Box.createHorizontalStrut(5));
    panel.add(lblTo);

    panel.add(javax.swing.Box.createHorizontalStrut(60));

    panel.add(lblChuyenKhoan);
    panel.add(javax.swing.Box.createHorizontalStrut(8));
    panel.add(txtChuyenKhoan);
    panel.add(javax.swing.Box.createHorizontalStrut(5));
    panel.add(lblDonVi);

    panel.revalidate();
    panel.repaint();
}


private int laySoTo(javax.swing.JTextField txt) {
    String s = txt.getText().trim();

    if (s.isEmpty()) {
        return 0;
    }

    try {
        return Integer.parseInt(s);
    } catch (NumberFormatException e) {
        return 0;
    }
}

private double layTienChuyenKhoan() {
    String s = jTextField7.getText().trim();

    if (s.isEmpty()) {
        return 0;
    }

    s = s.replace(".", "").replace(",", "");

    try {
        return Double.parseDouble(s);
    } catch (NumberFormatException e) {
        return 0;
    }
}

private double tinhTongTienKetCa() {
    double tong = 0;

    tong += laySoTo(jTextField1) * 1000;
    tong += laySoTo(jTextField2) * 2000;
    tong += laySoTo(jTextField3) * 5000;
    tong += laySoTo(jTextField4) * 10000;
    tong += laySoTo(jTextField5) * 20000;
    tong += laySoTo(jTextField6) * 50000;

    tong += laySoTo(jTextField13) * 100000;
    tong += laySoTo(jTextField11) * 200000;
    tong += laySoTo(jTextField14) * 500000;

    tong += layTienChuyenKhoan();

    return tong;
}

private String dinhDangTien(double soTien) {
    long tienLamTron = ((long) Math.floor(soTien / 1000.0)) * 1000;

    java.text.NumberFormat nf =
            java.text.NumberFormat.getInstance(new java.util.Locale("vi", "VN"));

    return nf.format(tienLamTron) + " VNĐ";
}
private void xacNhanKetCa() {
    double tongTien = tinhTongTienKetCa();

    String noiDung =
            "Xác nhận kết ca làm việc?\n\n"
            + "Nhân viên: " + jLabel3.getText() + "\n"
            + "Mã nhân viên: " + jLabel5.getText() + "\n"
            + "Ca làm: " + jLabel7.getText() + "\n"
            + "Thời gian kết ca: " + jLabel9.getText() + "\n"
            + "Thời gian làm việc: " + jLabel11.getText() + "\n\n"

            + "Chi tiết tiền cuối ca:\n"
            + "1.000₫ x " + laySoTo(jTextField1)
            + " = " + dinhDangTien(laySoTo(jTextField1) * 1000) + "\n"

            + "2.000₫ x " + laySoTo(jTextField2)
            + " = " + dinhDangTien(laySoTo(jTextField2) * 2000) + "\n"

            + "5.000₫ x " + laySoTo(jTextField3)
            + " = " + dinhDangTien(laySoTo(jTextField3) * 5000) + "\n"

            + "10.000₫ x " + laySoTo(jTextField4)
            + " = " + dinhDangTien(laySoTo(jTextField4) * 10000) + "\n"

            + "20.000₫ x " + laySoTo(jTextField5)
            + " = " + dinhDangTien(laySoTo(jTextField5) * 20000) + "\n"

            + "50.000₫ x " + laySoTo(jTextField6)
            + " = " + dinhDangTien(laySoTo(jTextField6) * 50000) + "\n"

            + "100.000₫ x " + laySoTo(jTextField13)
            + " = " + dinhDangTien(laySoTo(jTextField13) * 100000) + "\n"

            + "200.000₫ x " + laySoTo(jTextField11)
            + " = " + dinhDangTien(laySoTo(jTextField11) * 200000) + "\n"

            + "500.000₫ x " + laySoTo(jTextField14)
            + " = " + dinhDangTien(laySoTo(jTextField14) * 500000) + "\n"

            + "Tiền chuyển khoản: " + dinhDangTien(layTienChuyenKhoan()) + "\n\n"

            + "Tổng tiền kết ca: " + dinhDangTien(tongTien);

    Object[] luaChon = {"Xác nhận kết ca", "Hủy"};

    int chon = javax.swing.JOptionPane.showOptionDialog(
            this,
            noiDung,
            "Xác nhận kết ca",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE,
            null,
            luaChon,
            luaChon[0]
    );

    if (chon == 0) {
        this.ketCaThanhCong = true;
        this.tongTienKetCa = tongTien;
        dispose();
    }
}
    private String tinhThoiGianLamViec(
        java.time.LocalDateTime thoiGianBatDau,
        java.time.LocalDateTime thoiGianKetThuc
) {
    if (thoiGianBatDau == null || thoiGianKetThuc == null) {
        return "";
    }

    java.time.Duration duration =
            java.time.Duration.between(thoiGianBatDau, thoiGianKetThuc);

    long tongPhut = duration.toMinutes();

    if (tongPhut < 0) {
        return "";
    }

    long gio = tongPhut / 60;
    long phut = tongPhut % 60;

    if (gio > 0 && phut > 0) {
        return gio + " giờ " + phut + " phút";
    }

    if (gio > 0) {
        return gio + " giờ";
    }

    return phut + " phút";
}
    private void canChinhDongThongTinDoi(
        javax.swing.JPanel panel,
        javax.swing.JLabel lblTieuDe1,
        javax.swing.JLabel lblGiaTri1,
        javax.swing.JLabel lblTieuDe2,
        javax.swing.JLabel lblGiaTri2
) {
    panel.removeAll();
    panel.setLayout(new javax.swing.BoxLayout(panel, javax.swing.BoxLayout.X_AXIS));
    panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 5, 4, 5));
    panel.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 32));

    java.awt.Dimension sizeTieuDe = new java.awt.Dimension(120, 25);

    lblTieuDe1.setPreferredSize(sizeTieuDe);
    lblTieuDe1.setMinimumSize(sizeTieuDe);
    lblTieuDe1.setMaximumSize(sizeTieuDe);
    lblTieuDe1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));

    lblTieuDe2.setPreferredSize(new java.awt.Dimension(80, 25));
    lblTieuDe2.setMinimumSize(new java.awt.Dimension(80, 25));
    lblTieuDe2.setMaximumSize(new java.awt.Dimension(80, 25));
    lblTieuDe2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));

    lblGiaTri1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
    lblGiaTri1.setForeground(new java.awt.Color(0, 102, 204));

    lblGiaTri2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
    lblGiaTri2.setForeground(new java.awt.Color(0, 102, 204));

    panel.add(lblTieuDe1);
    panel.add(javax.swing.Box.createHorizontalStrut(8));
    panel.add(lblGiaTri1);

    panel.add(javax.swing.Box.createHorizontalStrut(70));

    panel.add(lblTieuDe2);
    panel.add(javax.swing.Box.createHorizontalStrut(8));
    panel.add(lblGiaTri2);

    panel.add(javax.swing.Box.createHorizontalGlue());

    panel.revalidate();
    panel.repaint();
}
    private void canChinhDongThongTinDon(
        javax.swing.JPanel panel,
        javax.swing.JLabel lblTieuDe,
        javax.swing.JLabel lblGiaTri
) {
    panel.removeAll();
    panel.setLayout(new javax.swing.BoxLayout(panel, javax.swing.BoxLayout.X_AXIS));
    panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 5, 4, 5));
    panel.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 32));

    lblTieuDe.setPreferredSize(new java.awt.Dimension(140, 25));
    lblTieuDe.setMinimumSize(new java.awt.Dimension(140, 25));
    lblTieuDe.setMaximumSize(new java.awt.Dimension(140, 25));
    lblTieuDe.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));

    lblGiaTri.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
    lblGiaTri.setForeground(new java.awt.Color(0, 102, 204));

    panel.add(lblTieuDe);
    panel.add(javax.swing.Box.createHorizontalStrut(8));
    panel.add(lblGiaTri);
    panel.add(javax.swing.Box.createHorizontalGlue());

    panel.revalidate();
    panel.repaint();
}
    private void canChinhDongNhanVienVaCaLam() {
    jPanel5.removeAll();
    jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.X_AXIS));
    jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(4, 5, 4, 5));
    jPanel5.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 32));

    jLabel2.setPreferredSize(new java.awt.Dimension(120, 25));
    jLabel2.setMinimumSize(new java.awt.Dimension(120, 25));
    jLabel2.setMaximumSize(new java.awt.Dimension(120, 25));
    jLabel2.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));

    jLabel6.setPreferredSize(new java.awt.Dimension(70, 25));
    jLabel6.setMinimumSize(new java.awt.Dimension(70, 25));
    jLabel6.setMaximumSize(new java.awt.Dimension(70, 25));
    jLabel6.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));

    jLabel3.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
    jLabel3.setForeground(new java.awt.Color(0, 102, 204));

    jLabel7.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
    jLabel7.setForeground(new java.awt.Color(0, 102, 204));

    jPanel5.add(jLabel2);
    jPanel5.add(javax.swing.Box.createHorizontalStrut(8));
    jPanel5.add(jLabel3);

    // Khoảng cách giữa tên nhân viên và chữ "Ca làm"
    jPanel5.add(javax.swing.Box.createHorizontalStrut(100));

    jPanel5.add(jLabel6);
    jPanel5.add(javax.swing.Box.createHorizontalStrut(8));
    jPanel5.add(jLabel7);

    jPanel5.add(javax.swing.Box.createHorizontalGlue());

    jPanel5.revalidate();
    jPanel5.repaint();
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
