/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.prj1.GUI;
import com.mycompany.prj1.ConnectDB.DB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import com.mycompany.prj1.DAO.DAO_NHANVIEN;
import com.mycompany.prj1.entity.NhanVien;

/**
 *
 * @author WINDOWS
 */
public class MoCa_ extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(MoCa_.class.getName());

    private String maNhanVien;
    private boolean moCaThanhCong = false;
    private long tongTienDauCa = 0;
    public MoCa_(java.awt.Frame parent, boolean modal, String maNhanVien) {
        super(parent, modal);
        this.maNhanVien = maNhanVien;

        initComponents();
        hienThiThongTinNhanVien(this.maNhanVien);
        hienThiThoiGianMoCa();
        canChinhGiaoDienMoCa();
        jButton1.addActionListener(e -> xacNhanMoCa());
        jButton2.addActionListener(e -> dispose());
    }

    public MoCa_(java.awt.Frame parent, boolean modal) {
        this(parent, modal, "");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mở ca làm việc");
        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mở ca làm việc");
        jLabel1.setAutoscrolls(true);
        getContentPane().add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.Y_AXIS));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thông tin nhân viên"));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));

        jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.LINE_AXIS));

        jLabel2.setText("Nhân viên:");
        jPanel5.add(jLabel2);

        jLabel3.setText("jLabel3");
        jPanel5.add(jLabel3);

        jPanel3.add(jPanel5);

        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.LINE_AXIS));

        jLabel4.setText("Mã nhân viên:");
        jPanel6.add(jLabel4);

        jLabel5.setText("jLabel5");
        jPanel6.add(jLabel5);

        jPanel3.add(jPanel6);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setText("Chức vụ: ");
        jPanel7.add(jLabel6);

        jLabel7.setText("jLabel7");
        jPanel7.add(jLabel7);

        jPanel3.add(jPanel7);

        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.X_AXIS));

        jLabel8.setText("Thời gian: ");
        jPanel17.add(jLabel8);

        jLabel9.setText("jLabel9");
        jPanel17.add(jLabel9);

        jPanel3.add(jPanel17);

        jPanel1.add(jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nhập số lượng tiền đầu ca"));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.X_AXIS));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/prj1/img/1nghin (1).jpg"))); // NOI18N
        jLabel10.setText("1.000₫  ");
        jPanel8.add(jLabel10);

        jTextField1.setText("jTextField1");
        jPanel8.add(jTextField1);

        jLabel12.setText("tờ");
        jPanel8.add(jLabel12);

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/prj1/img/100nghin (1).jpg"))); // NOI18N
        jLabel34.setText("100.000₫");
        jPanel8.add(jLabel34);

        jTextField13.setText("jTextField7");
        jPanel8.add(jTextField13);

        jLabel35.setText("tờ");
        jPanel8.add(jLabel35);

        jPanel4.add(jPanel8);

        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.X_AXIS));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/prj1/img/2nghin (1).jpg"))); // NOI18N
        jLabel11.setText("2.000₫  ");
        jPanel9.add(jLabel11);

        jTextField2.setText("jTextField2");
        jPanel9.add(jTextField2);

        jLabel13.setText("tờ");
        jPanel9.add(jLabel13);

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/prj1/img/200nghin (1).jpg"))); // NOI18N
        jLabel30.setText("200.000₫");
        jPanel9.add(jLabel30);

        jTextField11.setText("jTextField8");
        jPanel9.add(jTextField11);

        jLabel31.setText("tờ");
        jPanel9.add(jLabel31);

        jPanel4.add(jPanel9);

        jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.X_AXIS));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/prj1/img/5nghin (1).jpg"))); // NOI18N
        jLabel14.setText("5.000₫  ");
        jPanel10.add(jLabel14);

        jTextField3.setText("jTextField3");
        jPanel10.add(jTextField3);

        jLabel15.setText("tờ");
        jPanel10.add(jLabel15);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/prj1/img/500nghin (1).jpg"))); // NOI18N
        jLabel36.setText("500.000₫");
        jPanel10.add(jLabel36);

        jTextField14.setText("jTextField9");
        jPanel10.add(jTextField14);

        jLabel37.setText("tờ");
        jPanel10.add(jLabel37);

        jPanel4.add(jPanel10);

        jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.LINE_AXIS));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/prj1/img/10nghin (1).jpg"))); // NOI18N
        jLabel16.setText("10.000₫");
        jPanel11.add(jLabel16);

        jTextField4.setText("jTextField4");
        jPanel11.add(jTextField4);

        jLabel18.setText("tờ");
        jPanel11.add(jLabel18);

        jPanel4.add(jPanel11);

        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/prj1/img/20nghin (1).jpg"))); // NOI18N
        jLabel17.setText("20.000₫");
        jPanel12.add(jLabel17);

        jTextField5.setText("jTextField5");
        jPanel12.add(jTextField5);

        jLabel19.setText("tờ");
        jPanel12.add(jLabel19);

        jPanel4.add(jPanel12);

        jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.LINE_AXIS));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/prj1/img/50nghin (1).jpg"))); // NOI18N
        jLabel20.setText("50.000₫");
        jPanel13.add(jLabel20);

        jTextField6.setText("jTextField6");
        jPanel13.add(jTextField6);

        jLabel24.setText("tờ");
        jPanel13.add(jLabel24);

        jPanel4.add(jPanel13);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jButton1.setBackground(new java.awt.Color(51, 255, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(242, 242, 242));
        jButton1.setText("Mở ca");
        jPanel2.add(jButton1);

        jButton2.setText("Hủy");
        jPanel2.add(jButton2);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                MoCa_ dialog = new MoCa_(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    private void canChinhGiaoDienMoCa() {
    setSize(700, 670);
    setLocationRelativeTo(getParent());
    setResizable(false);

    jLabel1.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 22));
    jLabel1.setForeground(new java.awt.Color(0, 102, 204));
    jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(15, 0, 15, 0));

    jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 20, 10, 20));
    jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createTitledBorder(
                    javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)),
                    "Thông tin nhân viên"
            ),
            javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15)
    ));

    jPanel4.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createTitledBorder(
                    javax.swing.BorderFactory.createLineBorder(new java.awt.Color(180, 180, 180)),
                    "Nhập số lượng tiền đầu ca"
            ),
            javax.swing.BorderFactory.createEmptyBorder(10, 15, 10, 15)
    ));

    javax.swing.JPanel[] dongThongTin = {
        jPanel5, jPanel6, jPanel7, jPanel17
    };

    for (javax.swing.JPanel p : dongThongTin) {
        p.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 5, 6, 5));
        p.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 35));
    }

    javax.swing.JLabel[] labelTieuDe = {
        jLabel2, jLabel4, jLabel6, jLabel8
    };

    for (javax.swing.JLabel lbl : labelTieuDe) {
        lbl.setPreferredSize(new java.awt.Dimension(120, 25));
        lbl.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
    }

    javax.swing.JLabel[] labelGiaTri = {
        jLabel3, jLabel5, jLabel7, jLabel9
    };

    for (javax.swing.JLabel lbl : labelGiaTri) {
        lbl.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 13));
        lbl.setForeground(new java.awt.Color(0, 102, 204));
    }

    javax.swing.JPanel[] dongTien = {
    jPanel8, jPanel9, jPanel10, jPanel11, jPanel12, jPanel13
};

    for (javax.swing.JPanel p : dongTien) {
        p.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 5, 6, 5));
        p.setMaximumSize(new java.awt.Dimension(Integer.MAX_VALUE, 55));
    }

    javax.swing.JTextField[] txtTien = {
    jTextField1,   // 1.000
    jTextField2,   // 2.000
    jTextField3,   // 5.000
    jTextField4,   // 10.000
    jTextField5,   // 20.000
    jTextField6,   // 50.000
    jTextField13,  // 100.000
    jTextField11,  // 200.000
    jTextField14   // 500.000
};

    for (javax.swing.JTextField txt : txtTien) {
        txt.setText("0");
        txt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt.setPreferredSize(new java.awt.Dimension(90, 32));
        txt.setMaximumSize(new java.awt.Dimension(90, 32));
        txt.setMinimumSize(new java.awt.Dimension(90, 32));
        chiChoNhapSo(txt);
    }

    jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 15, 0));

    jButton1.setPreferredSize(new java.awt.Dimension(110, 35));
    jButton2.setPreferredSize(new java.awt.Dimension(110, 35));
    


// Căn khoảng cách giữa JLabel mệnh giá và JTextField nhập số tờ

canChinhDongTienDoi(
        jPanel8,
        jLabel10, jTextField1, jLabel12,
        jLabel34, jTextField13, jLabel35
);

canChinhDongTienDoi(
        jPanel9,
        jLabel11, jTextField2, jLabel13,
        jLabel30, jTextField11, jLabel31
);

canChinhDongTienDoi(
        jPanel10,
        jLabel14, jTextField3, jLabel15,
        jLabel36, jTextField14, jLabel37
);

canChinhDongTienDon(
        jPanel11,
        jLabel16, jTextField4, jLabel18
);

canChinhDongTienDon(
        jPanel12,
        jLabel17, jTextField5, jLabel19
);

canChinhDongTienDon(
        jPanel13,
        jLabel20, jTextField6, jLabel24
);
}
    private void hienThiThoiGianMoCa() {
    String thoiGian = LocalDateTime.now()
            .format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));

    jLabel9.setText(thoiGian);
}
    private void chiChoNhapSo(javax.swing.JTextField txt) {
    txt.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyTyped(java.awt.event.KeyEvent e) {
            char c = e.getKeyChar();
            if (!Character.isDigit(c)) {
                e.consume();
            }
        }
    });
}
    private void hienThiThongTinNhanVien(String maNhanVien) {
    DAO_NHANVIEN dao = new DAO_NHANVIEN();
    NhanVien nv = dao.layNhanVienTheoMa(maNhanVien);

    if (nv == null) {
        jLabel3.setText("Không tìm thấy");
        jLabel5.setText(maNhanVien);
        jLabel7.setText("");
        return;
    }

    jLabel3.setText(nv.getHoTenNV());       // Nhân viên
    jLabel5.setText(nv.getMaNhanVien());    // Mã nhân viên
    jLabel7.setText(nv.getChucVu());        // Chức vụ
}
    private int laySoTo(javax.swing.JTextField txt) {
    String s = txt.getText().trim();

    if (s.isEmpty()) {
        return 0;
    }

    try {
        return Integer.parseInt(s);
    } catch (NumberFormatException e) {
        return 0;
    }
}

private long tinhTongTienMoCa() {
    long tong = 0;

    tong += laySoTo(jTextField1) * 1000L;
    tong += laySoTo(jTextField2) * 2000L;
    tong += laySoTo(jTextField3) * 5000L;
    tong += laySoTo(jTextField4) * 10000L;
    tong += laySoTo(jTextField5) * 20000L;
    tong += laySoTo(jTextField6) * 50000L;

    tong += laySoTo(jTextField13) * 100000L;
    tong += laySoTo(jTextField11) * 200000L;
    tong += laySoTo(jTextField14) * 500000L;

    return tong;
}

private String dinhDangTien(long soTien) {
    java.text.NumberFormat nf =
            java.text.NumberFormat.getInstance(new java.util.Locale("vi", "VN"));

    return nf.format(soTien) + " ₫";
}
    private void xacNhanMoCa() {
    long tongTien = tinhTongTienMoCa();

    String noiDung =
            "Xác nhận mở ca làm việc?\n\n"
            + "Nhân viên: " + jLabel3.getText() + "\n"
            + "Mã nhân viên: " + jLabel5.getText() + "\n"
            + "Chức vụ: " + jLabel7.getText() + "\n"
            + "Thời gian mở ca: " + jLabel9.getText() + "\n\n"

            + "Chi tiết tiền đầu ca:\n"
            + "1.000₫ x " + laySoTo(jTextField1)
            + " = " + dinhDangTien(laySoTo(jTextField1) * 1000L) + "\n"

            + "2.000₫ x " + laySoTo(jTextField2)
            + " = " + dinhDangTien(laySoTo(jTextField2) * 2000L) + "\n"

            + "5.000₫ x " + laySoTo(jTextField3)
            + " = " + dinhDangTien(laySoTo(jTextField3) * 5000L) + "\n"

            + "10.000₫ x " + laySoTo(jTextField4)
            + " = " + dinhDangTien(laySoTo(jTextField4) * 10000L) + "\n"

            + "20.000₫ x " + laySoTo(jTextField5)
            + " = " + dinhDangTien(laySoTo(jTextField5) * 20000L) + "\n"

            + "50.000₫ x " + laySoTo(jTextField6)
            + " = " + dinhDangTien(laySoTo(jTextField6) * 50000L) + "\n"

            + "100.000₫ x " + laySoTo(jTextField13)
            + " = " + dinhDangTien(laySoTo(jTextField13) * 100000L) + "\n"

            + "200.000₫ x " + laySoTo(jTextField11)
            + " = " + dinhDangTien(laySoTo(jTextField11) * 200000L) + "\n"

            + "500.000₫ x " + laySoTo(jTextField14)
            + " = " + dinhDangTien(laySoTo(jTextField14) * 500000L) + "\n\n"

            + "Tổng tiền mở ca: " + dinhDangTien(tongTien);

    Object[] luaChon = {"Xác nhận", "Hủy"};

    int chon = javax.swing.JOptionPane.showOptionDialog(
            this,
            noiDung,
            "Xác nhận mở ca",
            javax.swing.JOptionPane.YES_NO_OPTION,
            javax.swing.JOptionPane.QUESTION_MESSAGE,
            null,
            luaChon,
            luaChon[0]
    );

    if (chon == 0) {
        this.tongTienDauCa = tongTien;
        this.moCaThanhCong = true;
        dispose();
    }
}
    private void canChinhDongTienDoi(
        javax.swing.JPanel panel,
        javax.swing.JLabel lbl1,
        javax.swing.JTextField txt1,
        javax.swing.JLabel lblTo1,
        javax.swing.JLabel lbl2,
        javax.swing.JTextField txt2,
        javax.swing.JLabel lblTo2
) {
    panel.removeAll();
    panel.setLayout(new javax.swing.BoxLayout(panel, javax.swing.BoxLayout.X_AXIS));

    panel.add(lbl1);
    panel.add(javax.swing.Box.createHorizontalStrut(8));  // cách JLabel với JTextField
    panel.add(txt1);
    panel.add(javax.swing.Box.createHorizontalStrut(5));
    panel.add(lblTo1);

    panel.add(javax.swing.Box.createHorizontalStrut(90)); // cách giữa 2 cụm tiền

    panel.add(lbl2);
    panel.add(javax.swing.Box.createHorizontalStrut(8));  // cách JLabel với JTextField
    panel.add(txt2);
    panel.add(javax.swing.Box.createHorizontalStrut(5));
    panel.add(lblTo2);

    panel.revalidate();
    panel.repaint();
}

private void canChinhDongTienDon(
        javax.swing.JPanel panel,
        javax.swing.JLabel lbl,
        javax.swing.JTextField txt,
        javax.swing.JLabel lblTo
) {
    panel.removeAll();
    panel.setLayout(new javax.swing.BoxLayout(panel, javax.swing.BoxLayout.X_AXIS));

    panel.add(lbl);
    panel.add(javax.swing.Box.createHorizontalStrut(8));  // cách JLabel với JTextField
    panel.add(txt);
    panel.add(javax.swing.Box.createHorizontalStrut(5));
    panel.add(lblTo);

    panel.revalidate();
    panel.repaint();
}
    public boolean isMoCaThanhCong() {
    return moCaThanhCong;
}

    public long getTongTienDauCa() {
    return tongTienDauCa;
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
